added missing folders, added new ultimate Makefile template for every advanced module's exercisses(auto push :heart:)

diff --git a/6/ex00/Makefile b/6/ex00/Makefile
--- a/6/ex00/Makefile
+++ b/6/ex00/Makefile
@@ -6,7 +6,7 @@
 #    By: lpeeters <lpeeters@student.s19.be>         +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
 #    Created: 2024/01/20 02:14:32 by lpeeters          #+#    #+#              #
-#    Updated: 2024/02/12 22:19:44 by lpeeters         ###   ########.fr        #
+#    Updated: 2024/06/05 23:45:36 by lpeeters         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
@@ -14,11 +14,13 @@ program_name = test
 
 compiler = c++
 
-compilation_flags = -g -Wall -Werror -Wextra -std=c++98
+compilation_flags = -g -Wall -Werror -Wextra
 
-source_files = ${shell find ./ -name "*.cpp"}
+project_flags = -std=c++98
 
-header_files = ${shell find ./ -name "*.hpp" -o -name "*.h"}
+source_files = ${foreach found_file,${shell find . -name "*.cpp"},${found_file:./%=%}}
+
+header_files = ${foreach found_file,${shell find . -name "*.h" -o -name "*.hpp" -o -name "*.tpp"},${found_file:./%=%}}
 
 header_directories = ${sort ${foreach header_path,${header_files},${dir ${header_path}}}}
 
@@ -44,15 +46,15 @@ up = \033[A
 # Erase the current line on the cursor
 clear = \033[K
 
-# Build dependency
+# Build dependencies
 program: ${program_name}
 
-# Build the executable
+# Build executable
 ${program_name}: ${source_files} ${header_files}
 	@echo "${yellow}compiling into executable...${white}"
 	@printf "${up}${clear}"
 	@if [ ! -e "${program_name}" ] && [ ! -d "${object_directory}" ]; then \
-		${compiler} ${compilation_flags} ${source_files} ${header_includes} -o ${program_name}; \
+		${compiler} ${compilation_flags} ${project_flags} ${source_files} ${header_includes} -o ${program_name}; \
 		if [ $$? -ne 0 ] || [ ! -e "${program_name}" ]; then \
 			echo "${red}error compiling executable${white}"; \
 		else \
@@ -60,7 +62,7 @@ ${program_name}: ${source_files} ${header_files}
 		fi \
 	else \
 		make -s obj; \
-		${compiler} ${compilation_flags} ${object_files} -o ${program_name}; \
+		${compiler} ${compilation_flags} ${project_flags} ${object_files} -o ${program_name}; \
 		if [ $$? -ne 0 ] || [ ! -e "${program_name}" ]; then \
 			echo "${red}error compiling object files${white}"; \
 		else \
@@ -78,13 +80,11 @@ ${object_directory}%.o: %.cpp ${header_files}
 	@if [ $$? -eq 0 ]; then \
 		printf "${up}${clear}"; \
 	fi
-	@${compiler} ${compilation_flags} -c $< ${header_includes} -o $@
-	@if [ "./${<:%.cpp=%.o}" = "${lastword ${source_files:%.cpp=%.o}}" ]; then \
-		if [ $$? -ne 0 ]; then \
-			echo "${red}error compiling object files${white}"; \
-		else \
-			echo "${green}done compiling object files${white}"; \
-		fi \
+	@${compiler} ${compilation_flags} ${project_flags} -c $< ${header_includes} -o $@
+	@if [ $$? -ne 0 ]; then \
+		echo "${red}error compiling object files${white}"; \
+	elif [ "${<:%.cpp=%.o}" = "${lastword ${source_files:%.cpp=%.o}}" ]; then \
+		echo "${green}done compiling object files${white}"; \
 	fi
 
 # If they exist, remove unecessary files for the final product
@@ -109,4 +109,4 @@ fclean: clean
 re: fclean program
 
 # Targets
-.PHONY: program obj clean fclean re
+.PHONY: compile_makefiles program obj clean fclean re
